/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as CollectionsUnder50RouteImport } from './routes/collections.under-50'
import { Route as CollectionsTrendingRouteImport } from './routes/collections.trending'
import { Route as CollectionsNewArrivalsRouteImport } from './routes/collections.new-arrivals'
import { Route as CollectionsGiftsRouteImport } from './routes/collections.gifts'
import { Route as CollectionsBestSellersRouteImport } from './routes/collections.best-sellers'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/shipping.lazy').then((d) => d.Route))
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/returns.lazy').then((d) => d.Route))
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/faq.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/account.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/products.$id.lazy').then((d) => d.Route))
const CollectionsUnder50Route = CollectionsUnder50RouteImport.update({
  id: '/under-50',
  path: '/under-50',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsTrendingRoute = CollectionsTrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsNewArrivalsRoute = CollectionsNewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsGiftsRoute = CollectionsGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => CollectionsRoute,
} as any)
const CollectionsBestSellersRoute = CollectionsBestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => CollectionsRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any).lazy(() =>
  import('./routes/account.wishlist.lazy').then((d) => d.Route),
)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any).lazy(() =>
  import('./routes/account.orders.lazy').then((d) => d.Route),
)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any).lazy(() =>
  import('./routes/account.addresses.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/shipping': typeof ShippingRoute
  '/size-guide': typeof SizeGuideRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/best-sellers': typeof CollectionsBestSellersRoute
  '/collections/gifts': typeof CollectionsGiftsRoute
  '/collections/new-arrivals': typeof CollectionsNewArrivalsRoute
  '/collections/trending': typeof CollectionsTrendingRoute
  '/collections/under-50': typeof CollectionsUnder50Route
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/shipping': typeof ShippingRoute
  '/size-guide': typeof SizeGuideRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/best-sellers': typeof CollectionsBestSellersRoute
  '/collections/gifts': typeof CollectionsGiftsRoute
  '/collections/new-arrivals': typeof CollectionsNewArrivalsRoute
  '/collections/trending': typeof CollectionsTrendingRoute
  '/collections/under-50': typeof CollectionsUnder50Route
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/shipping': typeof ShippingRoute
  '/size-guide': typeof SizeGuideRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/collections/best-sellers': typeof CollectionsBestSellersRoute
  '/collections/gifts': typeof CollectionsGiftsRoute
  '/collections/new-arrivals': typeof CollectionsNewArrivalsRoute
  '/collections/trending': typeof CollectionsTrendingRoute
  '/collections/under-50': typeof CollectionsUnder50Route
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/careers'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/faq'
    | '/help'
    | '/login'
    | '/press'
    | '/privacy'
    | '/returns'
    | '/sale'
    | '/shipping'
    | '/size-guide'
    | '/sustainability'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/category/$slug'
    | '/collections/best-sellers'
    | '/collections/gifts'
    | '/collections/new-arrivals'
    | '/collections/trending'
    | '/collections/under-50'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/careers'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/faq'
    | '/help'
    | '/login'
    | '/press'
    | '/privacy'
    | '/returns'
    | '/sale'
    | '/shipping'
    | '/size-guide'
    | '/sustainability'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/category/$slug'
    | '/collections/best-sellers'
    | '/collections/gifts'
    | '/collections/new-arrivals'
    | '/collections/trending'
    | '/collections/under-50'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/careers'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/faq'
    | '/help'
    | '/login'
    | '/press'
    | '/privacy'
    | '/returns'
    | '/sale'
    | '/shipping'
    | '/size-guide'
    | '/sustainability'
    | '/terms'
    | '/track-order'
    | '/wishlist'
    | '/account/addresses'
    | '/account/orders'
    | '/account/profile'
    | '/account/wishlist'
    | '/category/$slug'
    | '/collections/best-sellers'
    | '/collections/gifts'
    | '/collections/new-arrivals'
    | '/collections/trending'
    | '/collections/under-50'
    | '/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  SaleRoute: typeof SaleRoute
  ShippingRoute: typeof ShippingRoute
  SizeGuideRoute: typeof SizeGuideRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductsIdRoute: typeof ProductsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/under-50': {
      id: '/collections/under-50'
      path: '/under-50'
      fullPath: '/collections/under-50'
      preLoaderRoute: typeof CollectionsUnder50RouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/trending': {
      id: '/collections/trending'
      path: '/trending'
      fullPath: '/collections/trending'
      preLoaderRoute: typeof CollectionsTrendingRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/new-arrivals': {
      id: '/collections/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/collections/new-arrivals'
      preLoaderRoute: typeof CollectionsNewArrivalsRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/gifts': {
      id: '/collections/gifts'
      path: '/gifts'
      fullPath: '/collections/gifts'
      preLoaderRoute: typeof CollectionsGiftsRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/collections/best-sellers': {
      id: '/collections/best-sellers'
      path: '/best-sellers'
      fullPath: '/collections/best-sellers'
      preLoaderRoute: typeof CollectionsBestSellersRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountWishlistRoute: AccountWishlistRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CollectionsRouteChildren {
  CollectionsBestSellersRoute: typeof CollectionsBestSellersRoute
  CollectionsGiftsRoute: typeof CollectionsGiftsRoute
  CollectionsNewArrivalsRoute: typeof CollectionsNewArrivalsRoute
  CollectionsTrendingRoute: typeof CollectionsTrendingRoute
  CollectionsUnder50Route: typeof CollectionsUnder50Route
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsBestSellersRoute: CollectionsBestSellersRoute,
  CollectionsGiftsRoute: CollectionsGiftsRoute,
  CollectionsNewArrivalsRoute: CollectionsNewArrivalsRoute,
  CollectionsTrendingRoute: CollectionsTrendingRoute,
  CollectionsUnder50Route: CollectionsUnder50Route,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  SaleRoute: SaleRoute,
  ShippingRoute: ShippingRoute,
  SizeGuideRoute: SizeGuideRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductsIdRoute: ProductsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
